### ISSUE TITLE
yarn install fails on es-abstract 1.14.0 

### ISSUE THREAD

**Issue by arthurlutz** [Menturan/MMM-OpeningHours#25]
```
error An unexpected error occurred: "https://registry.yarnpkg.com/es-abstract/-/es-abstract-1.14.0.tgz: Request failed \"404 Not Found\"".
```

**Comment by arthurlutz** [comment]
There seems to be a workaround by using 1.14.1 (but I don't know how to generate the `integrity` attribute)

**Comment by Menturan** [comment]
Upgrading dependencies to latest version solved this issue. e51102cc705d1c2d85eb167456eec8ee7f72f1ac
