### ISSUE TITLE
Alias for long names

### ISSUE THREAD

**Issue by htilly** [Menturan/MMM-OpeningHours#3]
Awesome module, thanks for coding it!

Some places have quite long names. Suggestion to add optional "alias" for each PlaceID in the config.
If no "alias" is provided, the full name will be used.

Thanks in advance.

BR
Tilly

**Comment by DaVinki** [comment]
I Second this, because I have 2 supermarkets nearby with the same name. It would be handy if I could make a distinction between those 2. 

And indeed, a very awesome module! Keep it up!

**Comment by Menturan** [comment]
This feature has been added in a0531869d9879da709898d06d317f3396f1a5188.
Run the following commands 
```sh
$ git pull
$ yarn install
```
and update your config file. [See readme](https://github.com/Menturan/MMM-OpeningHours#places-config).
