### ISSUE TITLE
errors after installing

### ISSUE THREAD

**Issue by xCite1986** [Menturan/MMM-OpeningHours#4]
$ cd MagicMirror/modules
$ git clone https://github.com/Menturan/MMM-OpeningHours.git

after them i got following errors:

`0|MagicMir | App threw an error during load
0|MagicMir | Error: Cannot find module '@google/maps'
0|MagicMir |     at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
0|MagicMir |     at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
0|MagicMir |     at Function.Module._load (internal/modules/cjs/loader.js:528:25)
0|MagicMir |     at Module.require (internal/modules/cjs/loader.js:658:17)
0|MagicMir |     at require (internal/modules/cjs/helpers.js:20:18)
0|MagicMir |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-OpeningHours/node_helper.js:3:14)
0|MagicMir |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-OpeningHours/node_helper.js:133:3)
0|MagicMir |     at Module._compile (internal/modules/cjs/loader.js:711:30)
0|MagicMir |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
0|MagicMir |     at Module.load (internal/modules/cjs/loader.js:620:32)
0|MagicMir | Whoops! There was an uncaught exception...
0|MagicMir | { Error: Cannot find module '@google/maps'
0|MagicMir |     at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
0|MagicMir |     at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
0|MagicMir |     at Function.Module._load (internal/modules/cjs/loader.js:528:25)
0|MagicMir |     at Module.require (internal/modules/cjs/loader.js:658:17)
0|MagicMir |     at require (internal/modules/cjs/helpers.js:20:18)
0|MagicMir |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-OpeningHours/node_helper.js:3:14)
0|MagicMir |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-OpeningHours/node_helper.js:133:3)
0|MagicMir |     at Module._compile (internal/modules/cjs/loader.js:711:30)
0|MagicMir |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
0|MagicMir |     at Module.load (internal/modules/cjs/loader.js:620:32) code: 'MODULE_NOT_FOUND' }
`

anybody knows whats wrong?

**Comment by Menturan** [comment]
Did you run `yarn install`?

**Comment by xCite1986** [comment]
thanks for mental assistance :)
`sudo apt install yarn`, then a `yarn install` in ~/MagicMirror/modules/MMM-OpeningHours works flawlessly.
